server:
  port: 9060


spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/security-demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: "1234"

  devtools:  # 타임리프 변경 시 live reload되도록 하기
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/ # 소스 파일이 분산되어 있어서 지정필요
    cache: false
    check-template-location: true
    suffix: .html

#  web:
#    resources:
#      static-locations: